### ISSUE TITLE
J5 - Plugin causes failure deleting user

### ISSUE THREAD

**Issue by skurvish** [SharkyKZ/joomla-mvc-override-plugin#1]
First, let me say this plugin is amazing, so much easier than the earlier versions. 2 comments on it before I get to the issue at hand. First, it would be good if the comment under the New Class indicates that it must be a fully qualified class name like the overriden class name (took me a while to figure this one out). Second, it would also be nice if it was possible to enable/disable each override individually.

Now, on to the problem at hand. This plugin was working fine in J4. I upgraded my site to J5 and the plugin itself is working, but, when I attempt to delete a user I get an error. Disabling the mvcoverride plugin stopped the error, but I do need the plugin to be functional. I am not overriding any of these files. I have 2 overrides that affect Joomla\Component\Users\Site\Controller\RegistrationController and Joomla\Component\Users\Site\Model\RegistrationModel but the overrides themselves are pretty simple.

I can set you up to log in and test if you like. 

The error presented is: UserFactory not set in Joomla\Component\Users\Administrator\Model\UserModel

Here is the call stack on failure:

1 () JROOT/libraries/src/User/UserFactoryAwareTrait.php:45
2 Joomla\Component\Users\Administrator\Model\UserModel->getUserFactory() JROOT/administrator/components/com_users/src/Model/UserModel.php:333
3 Joomla\Component\Users\Administrator\Model\UserModel->delete() JROOT/libraries/src/MVC/Controller/AdminController.php:152
4 Joomla\CMS\MVC\Controller\AdminController->delete() JROOT/libraries/src/MVC/Controller/BaseController.php:730
5 Joomla\CMS\MVC\Controller\BaseController->execute() JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
6 Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() JROOT/libraries/src/Component/ComponentHelper.php:361
7 Joomla\CMS\Component\ComponentHelper::renderComponent() JROOT/libraries/src/Application/AdministratorApplication.php:150
8 Joomla\CMS\Application\AdministratorApplication->dispatch() JROOT/libraries/src/Application/AdministratorApplication.php:195
9 Joomla\CMS\Application\AdministratorApplication->doExecute() JROOT/libraries/src/Application/CMSApplication.php:306
10 Joomla\CMS\Application\CMSApplication->execute() JROOT/administrator/includes/app.php:58
11 require_once() JROOT/administrator/index.php:32

**Comment by skurvish** [comment]
I think the issue is somewhere in the MVCFactory override. When the component controller is dispatched the mvcFactory is set in the dispatcher and it is being correctly set as the mvcoverride MVCFactory. However, there are a number of traits that are not being initialized when the mvcfactory is constructed and I don't know why. With the plugin disabled all the traits are initialized, but with the plugin disabled ther are properly initialized.

I attempted to insert the interfaces on the class definition: implements MVCFactoryInterface, FormFactoryAwareInterface, SiteRouterAwareInterface, UserFactoryAwareInterface, MailerFactoryAwareInterface

and I added the following traits to the class:

    use FormFactoryAwareTrait;
    use DispatcherAwareTrait;
    use DatabaseAwareTrait;
    use SiteRouterAwareTrait;
    use CacheControllerFactoryAwareTrait;
    use UserFactoryAwareTrait;
    use MailerFactoryAwareTrait;

But they are still not initialized and this is why the UserFactory is not set.

At this point it is beyond my understanding of how all these interfaces and traits work, but perhaps my initial deep dive will point you in the right direction. I might also point out that the issue arises independently from what the override is. I have a controller and a model override. As long as one override exists the problem surfaces. I imagine this is a result of the plugin returning if no overrides exist.

Hope you can help.

**Comment by skurvish** [comment]
Just for further followup, I eventually went back to J4. Having done so I ran into more problems. For J5 I had adjusted my calls to get a user by ID to go through the container but this did not work on J4 for the same reason as described above, the UserFactory was not set in the container. I changed my calls back to Factory::getUser($id) and all seems to be OK for now.

But this should be addressed as it will not work on J5 and some J4 calls will fail.

**Comment by skurvish** [comment]
Back on J4 the problem has arisen again but now it is in creating a user. Deleting one seems to work OK. Clearly something different in the delet logic between J4 & J5.

**Comment by SharkyKZ** [comment]
To be honest, I don't recommend using this plugin or overriding core classes in general. For one, this plugin relies on implementation detail/private code which alone makes in unreliable. If you do need to override classes, you should at least use a specialized plugin. While some of the issues can be fixed in this plugin, it also depends on overrides being created correctly. The overridden classes would really need to be decorated for multiple plugins to interact correctly and this plugin has no control over it. I've written [an answer](https://joomla.stackexchange.com/a/33387/12652) relating to this on JSE.

**Comment by skurvish** [comment]
Thanks @SharkyKZ At this time the only thing that is not working for me is editing and deleting a user. I use Fabrik to create the user and it does not exhibit the issue. As my site does not have heavy traffic I will leave it as is and simply disable the mvc override plugin whenever I need to do either of those things.

Maybe some day another implementation will come along that will not have these issues. One can hope and dream.

**Comment by SharkyKZ** [comment]
Fixed this in https://github.com/SharkyKZ/joomla-mvc-override-plugin/commit/d19928e39d382c324324633d8c6ca9ba48facbb4 in a really ugly way. The plugin is still poorly written and I still don't recommend using it. But it should hold until more mandatory dependencies are introduced in J!

**Comment by skurvish** [comment]
Awesome, thanks.
