### ISSUE TITLE
Override model of fabrik 4.0

### ISSUE THREAD

**Issue by Diego-Godina** [SharkyKZ/joomla-mvc-override-plugin#2]
Hi!

I need override the class PlgFabrik_Element (components/com_fabrik/models/element.php) of fabrik 4.0 component but using this plugin the code breaks in:

// MVC factory not found or can't be overridden.
if (!$container->has(MVCFactoryInterface::class) || $container->isProtected(MVCFactoryInterface::class))
{
	return;
} 

Whats this means? What concess the hability to component to override?

The configurations that I put in the plugin are:
com_fabrik
Joomla\Component\Fabrik\Site\Model\PlgFabrik_Element
PlgFabrik_ElementExtraDatabasejoin
components/com_fabrik/models/element-extra-databasejoin.php

The file exists at directory and the class name ir right.

**Comment by SharkyKZ** [comment]
This plugin works with native J4 MVC components, particularly those using default MVC factory implementation. Fabrik uses J3 architecture so it's not supported. Secondly, the class in question is not even part of Fabrik's MVC stack, it does not use any sort of autoloading. It's loaded using `require_once` statement. So there's no sensible way of overriding it.
